### ISSUE TITLE
WiFi credentials can not be changed without resetting the device

### ISSUE THREAD

**Issue by YannickNagel** [sekassel/CoronaTrackerEsp32#21]
The saved WiFi credentials after initial setup are currently used forever and cannot be changed without restarting/resetting the device.

A solution would be to let the user reset the credentials (with a button click for example) and restart the [WifiManager-ConfigPortal](https://github.com/sekassel/CoronaTrackerEsp32/blob/f889470ccf4fb4507c2f1aede945e40cb798a054/tracker/src/coronatracker-wifi.cpp#L201) used at initial setup.

**Comment by M4XXX** [comment]
In my branch devNewBoardsCompatibility I added following functionality: Press Reset -> Hold Boot Button while startup and you will get a hotspot where you can reconfigure your wifi settings. Otherwise it will autoreconnect to given wifi network.
