### ISSUE TITLE
Device can not connect to WiFi after power loss

### ISSUE THREAD

**Issue by YannickNagel** [sekassel/CoronaTrackerEsp32#22]
After the ESP looses power, it can not connect to Wifi again and will start a WiFiManger-ConfigPortal. Because the [boolean flag](https://github.com/sekassel/CoronaTrackerEsp32/blob/f889470ccf4fb4507c2f1aede945e40cb798a054/tracker/src/main.cpp#L25) is saved in RTC memory, it is lost when the device resets.

A better solution would be to either store the flag more permanently or use ESP built-in functions to check WiFi status.

**Comment by ulno** [comment]
I think testing would be significantly simplified if a default WiFi could be selected in some kind of config.h - else this "bug" becomes quickly very annoying because of constant reconfiguration need.
