### ISSUE TITLE
Time displayed is always in CEST

### ISSUE THREAD

**Issue by YannickNagel** [sekassel/CoronaTrackerEsp32#24]
The [timezone offsets](https://github.com/sekassel/CoronaTrackerEsp32/blob/f889470ccf4fb4507c2f1aede945e40cb798a054/tracker/src/main.cpp#L44) are currently hard coded and result in displayed time always showing in CEST. While CWA is mainly used in Germany a better solution would be to configure these offsets, either manually or automatically.

**Comment by M4XXX** [comment]
Fixed with commit f6f5d447190c7d35811b7df33fcdb9b61cfe2a1c
