### ISSUE TITLE
No usage documentation

### ISSUE THREAD

**Issue by ulno** [sekassel/CoronaTrackerEsp32#34]
After some tweaking, I was able to compile and lash this project to my mhetesp32minikit board.
Initially I didn't see the display but that could be fixed with setting the right I2C pins.
However, I was wondering how the pressing of the button was affecting the display and also what I was supposed to see - so maybe a couple of lines in the documentation regarding usage could help here.

**Comment by YannickNagel** [comment]
Documentation was added in #32.
